// Copyright (c) 2022-2025 The Khronos Group Inc.
// Copyright (c) 2022-2025 Valve Corporation
// Copyright (c) 2022-2025 LunarG, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#version 450
#extension GL_GOOGLE_include_directive : enable

#include "common.h"
#include "push_data.h"

layout(push_constant) uniform UniformInfo {
    DispatchPushData pc;
};

layout(set = kValPipeDescSet, binding = kPreDispatchBinding_DispatchIndirectBuffer) buffer IndirectBuffer {
    uint indirect_buffer[];
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    const uint indirect_x = indirect_buffer[ pc.indirect_x_offset ];
    const uint indirect_y = indirect_buffer[ pc.indirect_x_offset + 1 ];
    const uint indirect_z = indirect_buffer[ pc.indirect_x_offset + 2 ];

    if (indirect_x > pc.limit_x) {
        GpuavLogError2(kErrorGroupGpuPreDispatch, kErrorSubCodePreDispatchCountLimitX, indirect_x, 0);
    } else if (indirect_y > pc.limit_y) {
        GpuavLogError2(kErrorGroupGpuPreDispatch, kErrorSubCodePreDispatchCountLimitY, indirect_y, 0);
    } else if (indirect_z > pc.limit_z) {
        GpuavLogError2(kErrorGroupGpuPreDispatch, kErrorSubCodePreDispatchCountLimitZ, indirect_z, 0);
    }
}
