/* Copyright (c) 2021 The Khronos Group Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author: Shahbaz Youssefi <syoussefi@google.com>
 **************************************************************************/
#pragma once

// This file serves the sole purpose of facilitating implementation of new extensions.  With
// work-in-program extensions, the relevant part of the Vulkan headers is not available until the
// extension is merged with the Vulkan registry.  Place that part from a manual generation of the
// headers in this file which is included in the autogenerated files where necessary.
//
// Together with updating registry/vk.xml in Vulkan-Headers and running
// `./scripts/generate_source.py /path/to/Vulkan-Headers/registry/`, the Mock ICD and DevSim (see
// docs/creating_tests.md#running-tests-on-devsim-and-mockicd), it's possible to implement
// validation for new extensions, write unit tests for it and execute them.
//
// Do NOT commit those changes to this file.
