#!/usr/bin/python3
#
# Copyright (c) 2023 LunarG, Inc.
# Copyright (c) 2023 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""An allowlist of codified VUIDs to autogenerate.  Currently, an allowlist is used to autogenerate
validation for VUIDs where the autogenerated code is verified to be bugfree.

Once the tooling around autogenerated codified VUs is stabilized, this should turn into a blocklist
as a safeguard to remove problematic VUs, if any."""

VU_ALLOWLIST = [
        'VUID-VkRenderingInfo-colorAttachmentCount-06097',
        'VUID-vkCmdClearColorImage-image-00002',
        'VUID-vkCmdClearColorImage-aspectMask-02498',
        'VUID-vkCmdClearColorImage-baseMipLevel-01470',
        'VUID-vkCmdClearColorImage-baseArrayLayer-01472',
        'VUID-vkCmdClearColorImage-pRanges-01692',
        'VUID-vkCmdClearColorImage-pRanges-01693',

        #'VUID-vkCreateComputePipelines-flags-00695', # Generator needs to add explicit casts
        #'VUID-vkCreateComputePipelines-flags-00696', # PreCallValidateCreateComputePipelines has
                                                      # extra args, codegen for these functions
                                                      # should call into ValidationStateTracker
                                                      # first and forward this argument.
        #'VUID-vkCreateComputePipelines-pipelineCache-02873', # PIPELINE_CACHE_STATE doesn't exist
        'VUID-vkCmdClearColorImage-imageLayout-00005',
        'VUID-vkCmdClearColorImage-imageLayout-01394',
        'VUID-vkCmdCopyBufferToImage-srcImage-00199',
        'VUID-vkCmdCopyImageToBuffer-srcImage-00199',
        'VUID-VkCopyBufferToImageInfo2-srcImage-00199',
        'VUID-VkCopyImageToBufferInfo2-srcImage-00199',
        'VUID-VkDescriptorSetLayoutCreateInfo-binding-00279',
        'VUID-VkDescriptorSetLayoutCreateInfo-flags-00280',
        'VUID-VkDescriptorSetLayoutCreateInfo-flags-02208',
        'VUID-VkDescriptorSetLayoutCreateInfo-flags-04590',
        'VUID-VkDescriptorSetLayoutCreateInfo-flags-04591',
        'VUID-VkDescriptorSetLayoutCreateInfo-flags-03000',
        'VUID-VkDescriptorSetLayoutCreateInfo-pBindings-07303',
        'VUID-VkDeviceCreateInfo-queueFamilyIndex-00372',
        'VUID-VkDeviceCreateInfo-queueFamilyIndex-02802',
]
