
// This file is ***GENERATED***.  Do Not Edit.
// See layer_chassis_generator.py for modifications.

/* Copyright (c) 2015-2021 The Khronos Group Inc.
 * Copyright (c) 2015-2021 Valve Corporation
 * Copyright (c) 2015-2021 LunarG, Inc.
 * Copyright (c) 2015-2021 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author: Mark Lobodzinski <mark@lunarg.com>
 * Author: Nadav Geva <nadav.geva@amd.com>
 */
#pragma once


// This source code creates dispatch vectors for each chassis api intercept,
// i.e., PreCallValidateFoo, PreCallRecordFoo, PostCallRecordFoo, etc., ensuring that 
// each vector contains only the validation objects that override that particular base 
// class virtual function. Preventing non-overridden calls from reaching the default
// functions saved about 5% in multithreaded applications.

typedef enum InterceptId{
    InterceptIdPreCallValidateGetDeviceQueue,
    InterceptIdPreCallRecordGetDeviceQueue,
    InterceptIdPostCallRecordGetDeviceQueue,
    InterceptIdPreCallValidateQueueSubmit,
    InterceptIdPreCallRecordQueueSubmit,
    InterceptIdPostCallRecordQueueSubmit,
    InterceptIdPreCallValidateQueueWaitIdle,
    InterceptIdPreCallRecordQueueWaitIdle,
    InterceptIdPostCallRecordQueueWaitIdle,
    InterceptIdPreCallValidateDeviceWaitIdle,
    InterceptIdPreCallRecordDeviceWaitIdle,
    InterceptIdPostCallRecordDeviceWaitIdle,
    InterceptIdPreCallValidateAllocateMemory,
    InterceptIdPreCallRecordAllocateMemory,
    InterceptIdPostCallRecordAllocateMemory,
    InterceptIdPreCallValidateMapMemory,
    InterceptIdPreCallRecordMapMemory,
    InterceptIdPostCallRecordMapMemory,
    InterceptIdPreCallValidateUnmapMemory,
    InterceptIdPreCallRecordUnmapMemory,
    InterceptIdPostCallRecordUnmapMemory,
    InterceptIdPreCallValidateFlushMappedMemoryRanges,
    InterceptIdPreCallRecordFlushMappedMemoryRanges,
    InterceptIdPostCallRecordFlushMappedMemoryRanges,
    InterceptIdPreCallValidateInvalidateMappedMemoryRanges,
    InterceptIdPreCallRecordInvalidateMappedMemoryRanges,
    InterceptIdPostCallRecordInvalidateMappedMemoryRanges,
    InterceptIdPreCallValidateGetDeviceMemoryCommitment,
    InterceptIdPreCallRecordGetDeviceMemoryCommitment,
    InterceptIdPostCallRecordGetDeviceMemoryCommitment,
    InterceptIdPreCallValidateBindBufferMemory,
    InterceptIdPreCallRecordBindBufferMemory,
    InterceptIdPostCallRecordBindBufferMemory,
    InterceptIdPreCallValidateBindImageMemory,
    InterceptIdPreCallRecordBindImageMemory,
    InterceptIdPostCallRecordBindImageMemory,
    InterceptIdPreCallValidateGetBufferMemoryRequirements,
    InterceptIdPreCallRecordGetBufferMemoryRequirements,
    InterceptIdPostCallRecordGetBufferMemoryRequirements,
    InterceptIdPreCallValidateGetImageMemoryRequirements,
    InterceptIdPreCallRecordGetImageMemoryRequirements,
    InterceptIdPostCallRecordGetImageMemoryRequirements,
    InterceptIdPreCallValidateCreateFence,
    InterceptIdPreCallRecordCreateFence,
    InterceptIdPostCallRecordCreateFence,
    InterceptIdPreCallValidateDestroyFence,
    InterceptIdPreCallRecordDestroyFence,
    InterceptIdPostCallRecordDestroyFence,
    InterceptIdPreCallValidateResetFences,
    InterceptIdPreCallRecordResetFences,
    InterceptIdPostCallRecordResetFences,
    InterceptIdPreCallValidateGetFenceStatus,
    InterceptIdPreCallRecordGetFenceStatus,
    InterceptIdPostCallRecordGetFenceStatus,
    InterceptIdPreCallValidateWaitForFences,
    InterceptIdPreCallRecordWaitForFences,
    InterceptIdPostCallRecordWaitForFences,
    InterceptIdPreCallValidateCreateSemaphore,
    InterceptIdPreCallRecordCreateSemaphore,
    InterceptIdPostCallRecordCreateSemaphore,
    InterceptIdPreCallValidateDestroySemaphore,
    InterceptIdPreCallRecordDestroySemaphore,
    InterceptIdPostCallRecordDestroySemaphore,
    InterceptIdPreCallValidateCreateEvent,
    InterceptIdPreCallRecordCreateEvent,
    InterceptIdPostCallRecordCreateEvent,
    InterceptIdPreCallValidateDestroyEvent,
    InterceptIdPreCallRecordDestroyEvent,
    InterceptIdPostCallRecordDestroyEvent,
    InterceptIdPreCallValidateGetEventStatus,
    InterceptIdPreCallRecordGetEventStatus,
    InterceptIdPostCallRecordGetEventStatus,
    InterceptIdPreCallValidateSetEvent,
    InterceptIdPreCallRecordSetEvent,
    InterceptIdPostCallRecordSetEvent,
    InterceptIdPreCallValidateResetEvent,
    InterceptIdPreCallRecordResetEvent,
    InterceptIdPostCallRecordResetEvent,
    InterceptIdPreCallValidateCreateQueryPool,
    InterceptIdPreCallRecordCreateQueryPool,
    InterceptIdPostCallRecordCreateQueryPool,
    InterceptIdPreCallValidateGetQueryPoolResults,
    InterceptIdPreCallRecordGetQueryPoolResults,
    InterceptIdPostCallRecordGetQueryPoolResults,
    InterceptIdPreCallValidateDestroyBuffer,
    InterceptIdPreCallRecordDestroyBuffer,
    InterceptIdPostCallRecordDestroyBuffer,
    InterceptIdPreCallValidateCreateBufferView,
    InterceptIdPreCallRecordCreateBufferView,
    InterceptIdPostCallRecordCreateBufferView,
    InterceptIdPreCallValidateDestroyBufferView,
    InterceptIdPreCallRecordDestroyBufferView,
    InterceptIdPostCallRecordDestroyBufferView,
    InterceptIdPreCallValidateCreateImage,
    InterceptIdPreCallRecordCreateImage,
    InterceptIdPostCallRecordCreateImage,
    InterceptIdPreCallValidateDestroyImage,
    InterceptIdPreCallRecordDestroyImage,
    InterceptIdPostCallRecordDestroyImage,
    InterceptIdPreCallValidateGetImageSubresourceLayout,
    InterceptIdPreCallRecordGetImageSubresourceLayout,
    InterceptIdPostCallRecordGetImageSubresourceLayout,
    InterceptIdPreCallValidateCreateImageView,
    InterceptIdPreCallRecordCreateImageView,
    InterceptIdPostCallRecordCreateImageView,
    InterceptIdPreCallValidateDestroyImageView,
    InterceptIdPreCallRecordDestroyImageView,
    InterceptIdPostCallRecordDestroyImageView,
    InterceptIdPreCallValidateCreatePipelineCache,
    InterceptIdPreCallRecordCreatePipelineCache,
    InterceptIdPostCallRecordCreatePipelineCache,
    InterceptIdPreCallValidateDestroyPipelineCache,
    InterceptIdPreCallRecordDestroyPipelineCache,
    InterceptIdPostCallRecordDestroyPipelineCache,
    InterceptIdPreCallValidateDestroyPipeline,
    InterceptIdPreCallRecordDestroyPipeline,
    InterceptIdPostCallRecordDestroyPipeline,
    InterceptIdPreCallValidateDestroyPipelineLayout,
    InterceptIdPreCallRecordDestroyPipelineLayout,
    InterceptIdPostCallRecordDestroyPipelineLayout,
    InterceptIdPreCallValidateCreateSampler,
    InterceptIdPreCallRecordCreateSampler,
    InterceptIdPostCallRecordCreateSampler,
    InterceptIdPreCallValidateDestroySampler,
    InterceptIdPreCallRecordDestroySampler,
    InterceptIdPostCallRecordDestroySampler,
    InterceptIdPreCallValidateCreateDescriptorSetLayout,
    InterceptIdPreCallRecordCreateDescriptorSetLayout,
    InterceptIdPostCallRecordCreateDescriptorSetLayout,
    InterceptIdPreCallValidateDestroyDescriptorSetLayout,
    InterceptIdPreCallRecordDestroyDescriptorSetLayout,
    InterceptIdPostCallRecordDestroyDescriptorSetLayout,
    InterceptIdPreCallValidateCreateDescriptorPool,
    InterceptIdPreCallRecordCreateDescriptorPool,
    InterceptIdPostCallRecordCreateDescriptorPool,
    InterceptIdPreCallValidateResetDescriptorPool,
    InterceptIdPreCallRecordResetDescriptorPool,
    InterceptIdPostCallRecordResetDescriptorPool,
    InterceptIdPreCallValidateFreeDescriptorSets,
    InterceptIdPreCallRecordFreeDescriptorSets,
    InterceptIdPostCallRecordFreeDescriptorSets,
    InterceptIdPreCallValidateUpdateDescriptorSets,
    InterceptIdPreCallRecordUpdateDescriptorSets,
    InterceptIdPostCallRecordUpdateDescriptorSets,
    InterceptIdPreCallValidateCreateFramebuffer,
    InterceptIdPreCallRecordCreateFramebuffer,
    InterceptIdPostCallRecordCreateFramebuffer,
    InterceptIdPreCallValidateDestroyFramebuffer,
    InterceptIdPreCallRecordDestroyFramebuffer,
    InterceptIdPostCallRecordDestroyFramebuffer,
    InterceptIdPreCallValidateCreateRenderPass,
    InterceptIdPreCallRecordCreateRenderPass,
    InterceptIdPostCallRecordCreateRenderPass,
    InterceptIdPreCallValidateDestroyRenderPass,
    InterceptIdPreCallRecordDestroyRenderPass,
    InterceptIdPostCallRecordDestroyRenderPass,
    InterceptIdPreCallValidateGetRenderAreaGranularity,
    InterceptIdPreCallRecordGetRenderAreaGranularity,
    InterceptIdPostCallRecordGetRenderAreaGranularity,
    InterceptIdPreCallValidateCreateCommandPool,
    InterceptIdPreCallRecordCreateCommandPool,
    InterceptIdPostCallRecordCreateCommandPool,
    InterceptIdPreCallValidateResetCommandPool,
    InterceptIdPreCallRecordResetCommandPool,
    InterceptIdPostCallRecordResetCommandPool,
    InterceptIdPreCallValidateAllocateCommandBuffers,
    InterceptIdPreCallRecordAllocateCommandBuffers,
    InterceptIdPostCallRecordAllocateCommandBuffers,
    InterceptIdPreCallValidateFreeCommandBuffers,
    InterceptIdPreCallRecordFreeCommandBuffers,
    InterceptIdPostCallRecordFreeCommandBuffers,
    InterceptIdPreCallValidateBeginCommandBuffer,
    InterceptIdPreCallRecordBeginCommandBuffer,
    InterceptIdPostCallRecordBeginCommandBuffer,
    InterceptIdPreCallValidateEndCommandBuffer,
    InterceptIdPreCallRecordEndCommandBuffer,
    InterceptIdPostCallRecordEndCommandBuffer,
    InterceptIdPreCallValidateResetCommandBuffer,
    InterceptIdPreCallRecordResetCommandBuffer,
    InterceptIdPostCallRecordResetCommandBuffer,
    InterceptIdPreCallValidateCmdBindPipeline,
    InterceptIdPreCallRecordCmdBindPipeline,
    InterceptIdPostCallRecordCmdBindPipeline,
    InterceptIdPreCallValidateCmdSetViewport,
    InterceptIdPreCallRecordCmdSetViewport,
    InterceptIdPostCallRecordCmdSetViewport,
    InterceptIdPreCallValidateCmdSetScissor,
    InterceptIdPreCallRecordCmdSetScissor,
    InterceptIdPostCallRecordCmdSetScissor,
    InterceptIdPreCallValidateCmdSetLineWidth,
    InterceptIdPreCallRecordCmdSetLineWidth,
    InterceptIdPostCallRecordCmdSetLineWidth,
    InterceptIdPreCallValidateCmdSetDepthBias,
    InterceptIdPreCallRecordCmdSetDepthBias,
    InterceptIdPostCallRecordCmdSetDepthBias,
    InterceptIdPreCallValidateCmdSetBlendConstants,
    InterceptIdPreCallRecordCmdSetBlendConstants,
    InterceptIdPostCallRecordCmdSetBlendConstants,
    InterceptIdPreCallValidateCmdSetDepthBounds,
    InterceptIdPreCallRecordCmdSetDepthBounds,
    InterceptIdPostCallRecordCmdSetDepthBounds,
    InterceptIdPreCallValidateCmdSetStencilCompareMask,
    InterceptIdPreCallRecordCmdSetStencilCompareMask,
    InterceptIdPostCallRecordCmdSetStencilCompareMask,
    InterceptIdPreCallValidateCmdSetStencilWriteMask,
    InterceptIdPreCallRecordCmdSetStencilWriteMask,
    InterceptIdPostCallRecordCmdSetStencilWriteMask,
    InterceptIdPreCallValidateCmdSetStencilReference,
    InterceptIdPreCallRecordCmdSetStencilReference,
    InterceptIdPostCallRecordCmdSetStencilReference,
    InterceptIdPreCallValidateCmdBindDescriptorSets,
    InterceptIdPreCallRecordCmdBindDescriptorSets,
    InterceptIdPostCallRecordCmdBindDescriptorSets,
    InterceptIdPreCallValidateCmdBindIndexBuffer,
    InterceptIdPreCallRecordCmdBindIndexBuffer,
    InterceptIdPostCallRecordCmdBindIndexBuffer,
    InterceptIdPreCallValidateCmdBindVertexBuffers,
    InterceptIdPreCallRecordCmdBindVertexBuffers,
    InterceptIdPostCallRecordCmdBindVertexBuffers,
    InterceptIdPreCallValidateCmdDraw,
    InterceptIdPreCallRecordCmdDraw,
    InterceptIdPostCallRecordCmdDraw,
    InterceptIdPreCallValidateCmdDrawIndexed,
    InterceptIdPreCallRecordCmdDrawIndexed,
    InterceptIdPostCallRecordCmdDrawIndexed,
    InterceptIdPreCallValidateCmdDrawIndirect,
    InterceptIdPreCallRecordCmdDrawIndirect,
    InterceptIdPostCallRecordCmdDrawIndirect,
    InterceptIdPreCallValidateCmdDrawIndexedIndirect,
    InterceptIdPreCallRecordCmdDrawIndexedIndirect,
    InterceptIdPostCallRecordCmdDrawIndexedIndirect,
    InterceptIdPreCallValidateCmdDispatch,
    InterceptIdPreCallRecordCmdDispatch,
    InterceptIdPostCallRecordCmdDispatch,
    InterceptIdPreCallValidateCmdDispatchIndirect,
    InterceptIdPreCallRecordCmdDispatchIndirect,
    InterceptIdPostCallRecordCmdDispatchIndirect,
    InterceptIdPreCallValidateCmdCopyBuffer,
    InterceptIdPreCallRecordCmdCopyBuffer,
    InterceptIdPostCallRecordCmdCopyBuffer,
    InterceptIdPreCallValidateCmdCopyImage,
    InterceptIdPreCallRecordCmdCopyImage,
    InterceptIdPostCallRecordCmdCopyImage,
    InterceptIdPreCallValidateCmdBlitImage,
    InterceptIdPreCallRecordCmdBlitImage,
    InterceptIdPostCallRecordCmdBlitImage,
    InterceptIdPreCallValidateCmdCopyBufferToImage,
    InterceptIdPreCallRecordCmdCopyBufferToImage,
    InterceptIdPostCallRecordCmdCopyBufferToImage,
    InterceptIdPreCallValidateCmdCopyImageToBuffer,
    InterceptIdPreCallRecordCmdCopyImageToBuffer,
    InterceptIdPostCallRecordCmdCopyImageToBuffer,
    InterceptIdPreCallValidateCmdUpdateBuffer,
    InterceptIdPreCallRecordCmdUpdateBuffer,
    InterceptIdPostCallRecordCmdUpdateBuffer,
    InterceptIdPreCallValidateCmdFillBuffer,
    InterceptIdPreCallRecordCmdFillBuffer,
    InterceptIdPostCallRecordCmdFillBuffer,
    InterceptIdPreCallValidateCmdClearColorImage,
    InterceptIdPreCallRecordCmdClearColorImage,
    InterceptIdPostCallRecordCmdClearColorImage,
    InterceptIdPreCallValidateCmdClearDepthStencilImage,
    InterceptIdPreCallRecordCmdClearDepthStencilImage,
    InterceptIdPostCallRecordCmdClearDepthStencilImage,
    InterceptIdPreCallValidateCmdClearAttachments,
    InterceptIdPreCallRecordCmdClearAttachments,
    InterceptIdPostCallRecordCmdClearAttachments,
    InterceptIdPreCallValidateCmdResolveImage,
    InterceptIdPreCallRecordCmdResolveImage,
    InterceptIdPostCallRecordCmdResolveImage,
    InterceptIdPreCallValidateCmdSetEvent,
    InterceptIdPreCallRecordCmdSetEvent,
    InterceptIdPostCallRecordCmdSetEvent,
    InterceptIdPreCallValidateCmdResetEvent,
    InterceptIdPreCallRecordCmdResetEvent,
    InterceptIdPostCallRecordCmdResetEvent,
    InterceptIdPreCallValidateCmdWaitEvents,
    InterceptIdPreCallRecordCmdWaitEvents,
    InterceptIdPostCallRecordCmdWaitEvents,
    InterceptIdPreCallValidateCmdPipelineBarrier,
    InterceptIdPreCallRecordCmdPipelineBarrier,
    InterceptIdPostCallRecordCmdPipelineBarrier,
    InterceptIdPreCallValidateCmdBeginQuery,
    InterceptIdPreCallRecordCmdBeginQuery,
    InterceptIdPostCallRecordCmdBeginQuery,
    InterceptIdPreCallValidateCmdEndQuery,
    InterceptIdPreCallRecordCmdEndQuery,
    InterceptIdPostCallRecordCmdEndQuery,
    InterceptIdPreCallValidateCmdResetQueryPool,
    InterceptIdPreCallRecordCmdResetQueryPool,
    InterceptIdPostCallRecordCmdResetQueryPool,
    InterceptIdPreCallValidateCmdWriteTimestamp,
    InterceptIdPreCallRecordCmdWriteTimestamp,
    InterceptIdPostCallRecordCmdWriteTimestamp,
    InterceptIdPreCallValidateCmdCopyQueryPoolResults,
    InterceptIdPreCallRecordCmdCopyQueryPoolResults,
    InterceptIdPostCallRecordCmdCopyQueryPoolResults,
    InterceptIdPreCallValidateCmdPushConstants,
    InterceptIdPreCallRecordCmdPushConstants,
    InterceptIdPostCallRecordCmdPushConstants,
    InterceptIdPreCallValidateCmdBeginRenderPass,
    InterceptIdPreCallRecordCmdBeginRenderPass,
    InterceptIdPostCallRecordCmdBeginRenderPass,
    InterceptIdPreCallValidateCmdNextSubpass,
    InterceptIdPreCallRecordCmdNextSubpass,
    InterceptIdPostCallRecordCmdNextSubpass,
    InterceptIdPreCallValidateCmdEndRenderPass,
    InterceptIdPreCallRecordCmdEndRenderPass,
    InterceptIdPostCallRecordCmdEndRenderPass,
    InterceptIdPreCallValidateCmdExecuteCommands,
    InterceptIdPreCallRecordCmdExecuteCommands,
    InterceptIdPostCallRecordCmdExecuteCommands,
    InterceptIdPreCallValidateBindBufferMemory2,
    InterceptIdPreCallRecordBindBufferMemory2,
    InterceptIdPostCallRecordBindBufferMemory2,
    InterceptIdPreCallValidateBindImageMemory2,
    InterceptIdPreCallRecordBindImageMemory2,
    InterceptIdPostCallRecordBindImageMemory2,
    InterceptIdPreCallValidateGetDeviceGroupPeerMemoryFeatures,
    InterceptIdPreCallRecordGetDeviceGroupPeerMemoryFeatures,
    InterceptIdPostCallRecordGetDeviceGroupPeerMemoryFeatures,
    InterceptIdPreCallValidateCmdSetDeviceMask,
    InterceptIdPreCallRecordCmdSetDeviceMask,
    InterceptIdPostCallRecordCmdSetDeviceMask,
    InterceptIdPreCallValidateCmdDispatchBase,
    InterceptIdPreCallRecordCmdDispatchBase,
    InterceptIdPostCallRecordCmdDispatchBase,
    InterceptIdPreCallValidateGetImageMemoryRequirements2,
    InterceptIdPreCallRecordGetImageMemoryRequirements2,
    InterceptIdPostCallRecordGetImageMemoryRequirements2,
    InterceptIdPreCallValidateGetBufferMemoryRequirements2,
    InterceptIdPreCallRecordGetBufferMemoryRequirements2,
    InterceptIdPostCallRecordGetBufferMemoryRequirements2,
    InterceptIdPreCallValidateGetDeviceQueue2,
    InterceptIdPreCallRecordGetDeviceQueue2,
    InterceptIdPostCallRecordGetDeviceQueue2,
    InterceptIdPreCallValidateCreateSamplerYcbcrConversion,
    InterceptIdPreCallRecordCreateSamplerYcbcrConversion,
    InterceptIdPostCallRecordCreateSamplerYcbcrConversion,
    InterceptIdPreCallValidateDestroySamplerYcbcrConversion,
    InterceptIdPreCallRecordDestroySamplerYcbcrConversion,
    InterceptIdPostCallRecordDestroySamplerYcbcrConversion,
    InterceptIdPreCallValidateGetDescriptorSetLayoutSupport,
    InterceptIdPreCallRecordGetDescriptorSetLayoutSupport,
    InterceptIdPostCallRecordGetDescriptorSetLayoutSupport,
    InterceptIdPreCallValidateCmdDrawIndirectCount,
    InterceptIdPreCallRecordCmdDrawIndirectCount,
    InterceptIdPostCallRecordCmdDrawIndirectCount,
    InterceptIdPreCallValidateCmdDrawIndexedIndirectCount,
    InterceptIdPreCallRecordCmdDrawIndexedIndirectCount,
    InterceptIdPostCallRecordCmdDrawIndexedIndirectCount,
    InterceptIdPreCallValidateCreateRenderPass2,
    InterceptIdPreCallRecordCreateRenderPass2,
    InterceptIdPostCallRecordCreateRenderPass2,
    InterceptIdPreCallValidateCmdBeginRenderPass2,
    InterceptIdPreCallRecordCmdBeginRenderPass2,
    InterceptIdPostCallRecordCmdBeginRenderPass2,
    InterceptIdPreCallValidateCmdNextSubpass2,
    InterceptIdPreCallRecordCmdNextSubpass2,
    InterceptIdPostCallRecordCmdNextSubpass2,
    InterceptIdPreCallValidateCmdEndRenderPass2,
    InterceptIdPreCallRecordCmdEndRenderPass2,
    InterceptIdPostCallRecordCmdEndRenderPass2,
    InterceptIdPreCallValidateResetQueryPool,
    InterceptIdPreCallRecordResetQueryPool,
    InterceptIdPostCallRecordResetQueryPool,
    InterceptIdPreCallValidateGetSemaphoreCounterValue,
    InterceptIdPreCallRecordGetSemaphoreCounterValue,
    InterceptIdPostCallRecordGetSemaphoreCounterValue,
    InterceptIdPreCallValidateWaitSemaphores,
    InterceptIdPreCallRecordWaitSemaphores,
    InterceptIdPostCallRecordWaitSemaphores,
    InterceptIdPreCallValidateSignalSemaphore,
    InterceptIdPreCallRecordSignalSemaphore,
    InterceptIdPostCallRecordSignalSemaphore,
    InterceptIdPreCallValidateGetBufferDeviceAddress,
    InterceptIdPreCallRecordGetBufferDeviceAddress,
    InterceptIdPostCallRecordGetBufferDeviceAddress,
    InterceptIdPreCallValidateGetBufferOpaqueCaptureAddress,
    InterceptIdPreCallRecordGetBufferOpaqueCaptureAddress,
    InterceptIdPostCallRecordGetBufferOpaqueCaptureAddress,
    InterceptIdPreCallValidateGetDeviceMemoryOpaqueCaptureAddress,
    InterceptIdPreCallRecordGetDeviceMemoryOpaqueCaptureAddress,
    InterceptIdPostCallRecordGetDeviceMemoryOpaqueCaptureAddress,
    InterceptIdPreCallValidateGetCommandPoolMemoryConsumption,
    InterceptIdPreCallRecordGetCommandPoolMemoryConsumption,
    InterceptIdPostCallRecordGetCommandPoolMemoryConsumption,
    InterceptIdPreCallValidateGetFaultData,
    InterceptIdPreCallRecordGetFaultData,
    InterceptIdPostCallRecordGetFaultData,
    InterceptIdPreCallValidateCreateSwapchainKHR,
    InterceptIdPreCallRecordCreateSwapchainKHR,
    InterceptIdPostCallRecordCreateSwapchainKHR,
    InterceptIdPreCallValidateGetSwapchainImagesKHR,
    InterceptIdPreCallRecordGetSwapchainImagesKHR,
    InterceptIdPostCallRecordGetSwapchainImagesKHR,
    InterceptIdPreCallValidateAcquireNextImageKHR,
    InterceptIdPreCallRecordAcquireNextImageKHR,
    InterceptIdPostCallRecordAcquireNextImageKHR,
    InterceptIdPreCallValidateQueuePresentKHR,
    InterceptIdPreCallRecordQueuePresentKHR,
    InterceptIdPostCallRecordQueuePresentKHR,
    InterceptIdPreCallValidateGetDeviceGroupPresentCapabilitiesKHR,
    InterceptIdPreCallRecordGetDeviceGroupPresentCapabilitiesKHR,
    InterceptIdPostCallRecordGetDeviceGroupPresentCapabilitiesKHR,
    InterceptIdPreCallValidateGetDeviceGroupSurfacePresentModesKHR,
    InterceptIdPreCallRecordGetDeviceGroupSurfacePresentModesKHR,
    InterceptIdPostCallRecordGetDeviceGroupSurfacePresentModesKHR,
    InterceptIdPreCallValidateAcquireNextImage2KHR,
    InterceptIdPreCallRecordAcquireNextImage2KHR,
    InterceptIdPostCallRecordAcquireNextImage2KHR,
    InterceptIdPreCallValidateCreateSharedSwapchainsKHR,
    InterceptIdPreCallRecordCreateSharedSwapchainsKHR,
    InterceptIdPostCallRecordCreateSharedSwapchainsKHR,
    InterceptIdPreCallValidateGetMemoryFdKHR,
    InterceptIdPreCallRecordGetMemoryFdKHR,
    InterceptIdPostCallRecordGetMemoryFdKHR,
    InterceptIdPreCallValidateGetMemoryFdPropertiesKHR,
    InterceptIdPreCallRecordGetMemoryFdPropertiesKHR,
    InterceptIdPostCallRecordGetMemoryFdPropertiesKHR,
    InterceptIdPreCallValidateImportSemaphoreFdKHR,
    InterceptIdPreCallRecordImportSemaphoreFdKHR,
    InterceptIdPostCallRecordImportSemaphoreFdKHR,
    InterceptIdPreCallValidateGetSemaphoreFdKHR,
    InterceptIdPreCallRecordGetSemaphoreFdKHR,
    InterceptIdPostCallRecordGetSemaphoreFdKHR,
    InterceptIdPreCallValidateGetSwapchainStatusKHR,
    InterceptIdPreCallRecordGetSwapchainStatusKHR,
    InterceptIdPostCallRecordGetSwapchainStatusKHR,
    InterceptIdPreCallValidateImportFenceFdKHR,
    InterceptIdPreCallRecordImportFenceFdKHR,
    InterceptIdPostCallRecordImportFenceFdKHR,
    InterceptIdPreCallValidateGetFenceFdKHR,
    InterceptIdPreCallRecordGetFenceFdKHR,
    InterceptIdPostCallRecordGetFenceFdKHR,
    InterceptIdPreCallValidateAcquireProfilingLockKHR,
    InterceptIdPreCallRecordAcquireProfilingLockKHR,
    InterceptIdPostCallRecordAcquireProfilingLockKHR,
    InterceptIdPreCallValidateReleaseProfilingLockKHR,
    InterceptIdPreCallRecordReleaseProfilingLockKHR,
    InterceptIdPostCallRecordReleaseProfilingLockKHR,
    InterceptIdPreCallValidateCmdSetFragmentShadingRateKHR,
    InterceptIdPreCallRecordCmdSetFragmentShadingRateKHR,
    InterceptIdPostCallRecordCmdSetFragmentShadingRateKHR,
    InterceptIdPreCallValidateCmdRefreshObjectsKHR,
    InterceptIdPreCallRecordCmdRefreshObjectsKHR,
    InterceptIdPostCallRecordCmdRefreshObjectsKHR,
    InterceptIdPreCallValidateCmdSetEvent2KHR,
    InterceptIdPreCallRecordCmdSetEvent2KHR,
    InterceptIdPostCallRecordCmdSetEvent2KHR,
    InterceptIdPreCallValidateCmdResetEvent2KHR,
    InterceptIdPreCallRecordCmdResetEvent2KHR,
    InterceptIdPostCallRecordCmdResetEvent2KHR,
    InterceptIdPreCallValidateCmdWaitEvents2KHR,
    InterceptIdPreCallRecordCmdWaitEvents2KHR,
    InterceptIdPostCallRecordCmdWaitEvents2KHR,
    InterceptIdPreCallValidateCmdPipelineBarrier2KHR,
    InterceptIdPreCallRecordCmdPipelineBarrier2KHR,
    InterceptIdPostCallRecordCmdPipelineBarrier2KHR,
    InterceptIdPreCallValidateCmdWriteTimestamp2KHR,
    InterceptIdPreCallRecordCmdWriteTimestamp2KHR,
    InterceptIdPostCallRecordCmdWriteTimestamp2KHR,
    InterceptIdPreCallValidateQueueSubmit2KHR,
    InterceptIdPreCallRecordQueueSubmit2KHR,
    InterceptIdPostCallRecordQueueSubmit2KHR,
    InterceptIdPreCallValidateCmdWriteBufferMarker2AMD,
    InterceptIdPreCallRecordCmdWriteBufferMarker2AMD,
    InterceptIdPostCallRecordCmdWriteBufferMarker2AMD,
    InterceptIdPreCallValidateGetQueueCheckpointData2NV,
    InterceptIdPreCallRecordGetQueueCheckpointData2NV,
    InterceptIdPostCallRecordGetQueueCheckpointData2NV,
    InterceptIdPreCallValidateCmdCopyBuffer2KHR,
    InterceptIdPreCallRecordCmdCopyBuffer2KHR,
    InterceptIdPostCallRecordCmdCopyBuffer2KHR,
    InterceptIdPreCallValidateCmdCopyImage2KHR,
    InterceptIdPreCallRecordCmdCopyImage2KHR,
    InterceptIdPostCallRecordCmdCopyImage2KHR,
    InterceptIdPreCallValidateCmdCopyBufferToImage2KHR,
    InterceptIdPreCallRecordCmdCopyBufferToImage2KHR,
    InterceptIdPostCallRecordCmdCopyBufferToImage2KHR,
    InterceptIdPreCallValidateCmdCopyImageToBuffer2KHR,
    InterceptIdPreCallRecordCmdCopyImageToBuffer2KHR,
    InterceptIdPostCallRecordCmdCopyImageToBuffer2KHR,
    InterceptIdPreCallValidateCmdBlitImage2KHR,
    InterceptIdPreCallRecordCmdBlitImage2KHR,
    InterceptIdPostCallRecordCmdBlitImage2KHR,
    InterceptIdPreCallValidateCmdResolveImage2KHR,
    InterceptIdPreCallRecordCmdResolveImage2KHR,
    InterceptIdPostCallRecordCmdResolveImage2KHR,
    InterceptIdPreCallValidateDisplayPowerControlEXT,
    InterceptIdPreCallRecordDisplayPowerControlEXT,
    InterceptIdPostCallRecordDisplayPowerControlEXT,
    InterceptIdPreCallValidateRegisterDeviceEventEXT,
    InterceptIdPreCallRecordRegisterDeviceEventEXT,
    InterceptIdPostCallRecordRegisterDeviceEventEXT,
    InterceptIdPreCallValidateRegisterDisplayEventEXT,
    InterceptIdPreCallRecordRegisterDisplayEventEXT,
    InterceptIdPostCallRecordRegisterDisplayEventEXT,
    InterceptIdPreCallValidateGetSwapchainCounterEXT,
    InterceptIdPreCallRecordGetSwapchainCounterEXT,
    InterceptIdPostCallRecordGetSwapchainCounterEXT,
    InterceptIdPreCallValidateCmdSetDiscardRectangleEXT,
    InterceptIdPreCallRecordCmdSetDiscardRectangleEXT,
    InterceptIdPostCallRecordCmdSetDiscardRectangleEXT,
    InterceptIdPreCallValidateSetHdrMetadataEXT,
    InterceptIdPreCallRecordSetHdrMetadataEXT,
    InterceptIdPostCallRecordSetHdrMetadataEXT,
    InterceptIdPreCallValidateSetDebugUtilsObjectNameEXT,
    InterceptIdPreCallRecordSetDebugUtilsObjectNameEXT,
    InterceptIdPostCallRecordSetDebugUtilsObjectNameEXT,
    InterceptIdPreCallValidateSetDebugUtilsObjectTagEXT,
    InterceptIdPreCallRecordSetDebugUtilsObjectTagEXT,
    InterceptIdPostCallRecordSetDebugUtilsObjectTagEXT,
    InterceptIdPreCallValidateQueueBeginDebugUtilsLabelEXT,
    InterceptIdPreCallRecordQueueBeginDebugUtilsLabelEXT,
    InterceptIdPostCallRecordQueueBeginDebugUtilsLabelEXT,
    InterceptIdPreCallValidateQueueEndDebugUtilsLabelEXT,
    InterceptIdPreCallRecordQueueEndDebugUtilsLabelEXT,
    InterceptIdPostCallRecordQueueEndDebugUtilsLabelEXT,
    InterceptIdPreCallValidateQueueInsertDebugUtilsLabelEXT,
    InterceptIdPreCallRecordQueueInsertDebugUtilsLabelEXT,
    InterceptIdPostCallRecordQueueInsertDebugUtilsLabelEXT,
    InterceptIdPreCallValidateCmdBeginDebugUtilsLabelEXT,
    InterceptIdPreCallRecordCmdBeginDebugUtilsLabelEXT,
    InterceptIdPostCallRecordCmdBeginDebugUtilsLabelEXT,
    InterceptIdPreCallValidateCmdEndDebugUtilsLabelEXT,
    InterceptIdPreCallRecordCmdEndDebugUtilsLabelEXT,
    InterceptIdPostCallRecordCmdEndDebugUtilsLabelEXT,
    InterceptIdPreCallValidateCmdInsertDebugUtilsLabelEXT,
    InterceptIdPreCallRecordCmdInsertDebugUtilsLabelEXT,
    InterceptIdPostCallRecordCmdInsertDebugUtilsLabelEXT,
    InterceptIdPreCallValidateCmdSetSampleLocationsEXT,
    InterceptIdPreCallRecordCmdSetSampleLocationsEXT,
    InterceptIdPostCallRecordCmdSetSampleLocationsEXT,
    InterceptIdPreCallValidateGetImageDrmFormatModifierPropertiesEXT,
    InterceptIdPreCallRecordGetImageDrmFormatModifierPropertiesEXT,
    InterceptIdPostCallRecordGetImageDrmFormatModifierPropertiesEXT,
    InterceptIdPreCallValidateGetMemoryHostPointerPropertiesEXT,
    InterceptIdPreCallRecordGetMemoryHostPointerPropertiesEXT,
    InterceptIdPostCallRecordGetMemoryHostPointerPropertiesEXT,
    InterceptIdPreCallValidateGetCalibratedTimestampsEXT,
    InterceptIdPreCallRecordGetCalibratedTimestampsEXT,
    InterceptIdPostCallRecordGetCalibratedTimestampsEXT,
    InterceptIdPreCallValidateCmdSetLineStippleEXT,
    InterceptIdPreCallRecordCmdSetLineStippleEXT,
    InterceptIdPostCallRecordCmdSetLineStippleEXT,
    InterceptIdPreCallValidateCmdSetCullModeEXT,
    InterceptIdPreCallRecordCmdSetCullModeEXT,
    InterceptIdPostCallRecordCmdSetCullModeEXT,
    InterceptIdPreCallValidateCmdSetFrontFaceEXT,
    InterceptIdPreCallRecordCmdSetFrontFaceEXT,
    InterceptIdPostCallRecordCmdSetFrontFaceEXT,
    InterceptIdPreCallValidateCmdSetPrimitiveTopologyEXT,
    InterceptIdPreCallRecordCmdSetPrimitiveTopologyEXT,
    InterceptIdPostCallRecordCmdSetPrimitiveTopologyEXT,
    InterceptIdPreCallValidateCmdSetViewportWithCountEXT,
    InterceptIdPreCallRecordCmdSetViewportWithCountEXT,
    InterceptIdPostCallRecordCmdSetViewportWithCountEXT,
    InterceptIdPreCallValidateCmdSetScissorWithCountEXT,
    InterceptIdPreCallRecordCmdSetScissorWithCountEXT,
    InterceptIdPostCallRecordCmdSetScissorWithCountEXT,
    InterceptIdPreCallValidateCmdBindVertexBuffers2EXT,
    InterceptIdPreCallRecordCmdBindVertexBuffers2EXT,
    InterceptIdPostCallRecordCmdBindVertexBuffers2EXT,
    InterceptIdPreCallValidateCmdSetDepthTestEnableEXT,
    InterceptIdPreCallRecordCmdSetDepthTestEnableEXT,
    InterceptIdPostCallRecordCmdSetDepthTestEnableEXT,
    InterceptIdPreCallValidateCmdSetDepthWriteEnableEXT,
    InterceptIdPreCallRecordCmdSetDepthWriteEnableEXT,
    InterceptIdPostCallRecordCmdSetDepthWriteEnableEXT,
    InterceptIdPreCallValidateCmdSetDepthCompareOpEXT,
    InterceptIdPreCallRecordCmdSetDepthCompareOpEXT,
    InterceptIdPostCallRecordCmdSetDepthCompareOpEXT,
    InterceptIdPreCallValidateCmdSetDepthBoundsTestEnableEXT,
    InterceptIdPreCallRecordCmdSetDepthBoundsTestEnableEXT,
    InterceptIdPostCallRecordCmdSetDepthBoundsTestEnableEXT,
    InterceptIdPreCallValidateCmdSetStencilTestEnableEXT,
    InterceptIdPreCallRecordCmdSetStencilTestEnableEXT,
    InterceptIdPostCallRecordCmdSetStencilTestEnableEXT,
    InterceptIdPreCallValidateCmdSetStencilOpEXT,
    InterceptIdPreCallRecordCmdSetStencilOpEXT,
    InterceptIdPostCallRecordCmdSetStencilOpEXT,
    InterceptIdPreCallValidateCmdSetVertexInputEXT,
    InterceptIdPreCallRecordCmdSetVertexInputEXT,
    InterceptIdPostCallRecordCmdSetVertexInputEXT,
    InterceptIdPreCallValidateGetFenceSciSyncFenceNV,
    InterceptIdPreCallRecordGetFenceSciSyncFenceNV,
    InterceptIdPostCallRecordGetFenceSciSyncFenceNV,
    InterceptIdPreCallValidateGetFenceSciSyncObjNV,
    InterceptIdPreCallRecordGetFenceSciSyncObjNV,
    InterceptIdPostCallRecordGetFenceSciSyncObjNV,
    InterceptIdPreCallValidateImportFenceSciSyncFenceNV,
    InterceptIdPreCallRecordImportFenceSciSyncFenceNV,
    InterceptIdPostCallRecordImportFenceSciSyncFenceNV,
    InterceptIdPreCallValidateImportFenceSciSyncObjNV,
    InterceptIdPreCallRecordImportFenceSciSyncObjNV,
    InterceptIdPostCallRecordImportFenceSciSyncObjNV,
    InterceptIdPreCallValidateGetSemaphoreSciSyncObjNV,
    InterceptIdPreCallRecordGetSemaphoreSciSyncObjNV,
    InterceptIdPostCallRecordGetSemaphoreSciSyncObjNV,
    InterceptIdPreCallValidateImportSemaphoreSciSyncObjNV,
    InterceptIdPreCallRecordImportSemaphoreSciSyncObjNV,
    InterceptIdPostCallRecordImportSemaphoreSciSyncObjNV,
    InterceptIdPreCallValidateGetMemorySciBufNV,
    InterceptIdPreCallRecordGetMemorySciBufNV,
    InterceptIdPostCallRecordGetMemorySciBufNV,
    InterceptIdPreCallValidateCmdSetPatchControlPointsEXT,
    InterceptIdPreCallRecordCmdSetPatchControlPointsEXT,
    InterceptIdPostCallRecordCmdSetPatchControlPointsEXT,
    InterceptIdPreCallValidateCmdSetRasterizerDiscardEnableEXT,
    InterceptIdPreCallRecordCmdSetRasterizerDiscardEnableEXT,
    InterceptIdPostCallRecordCmdSetRasterizerDiscardEnableEXT,
    InterceptIdPreCallValidateCmdSetDepthBiasEnableEXT,
    InterceptIdPreCallRecordCmdSetDepthBiasEnableEXT,
    InterceptIdPostCallRecordCmdSetDepthBiasEnableEXT,
    InterceptIdPreCallValidateCmdSetLogicOpEXT,
    InterceptIdPreCallRecordCmdSetLogicOpEXT,
    InterceptIdPostCallRecordCmdSetLogicOpEXT,
    InterceptIdPreCallValidateCmdSetPrimitiveRestartEnableEXT,
    InterceptIdPreCallRecordCmdSetPrimitiveRestartEnableEXT,
    InterceptIdPostCallRecordCmdSetPrimitiveRestartEnableEXT,
    InterceptIdPreCallValidateCmdSetColorWriteEnableEXT,
    InterceptIdPreCallRecordCmdSetColorWriteEnableEXT,
    InterceptIdPostCallRecordCmdSetColorWriteEnableEXT,
    InterceptIdCount,
} InterceptId;



void ValidationObject::InitObjectDispatchVectors() {

#if !defined(VULKANSC)
#define BUILD_DISPATCH_VECTOR(name) \
    init_object_dispatch_vector(InterceptId ## name, \
                                typeid(&ValidationObject::name), \
                                typeid(&ThreadSafety::name), \
                                typeid(&StatelessValidation::name), \
                                typeid(&ObjectLifetimes::name), \
                                typeid(&CoreChecks::name), \
                                typeid(&BestPractices::name), \
                                typeid(&GpuAssisted::name), \
                                typeid(&DebugPrintf::name), \
                                typeid(&SyncValidator::name));
#else
#define BUILD_DISPATCH_VECTOR(name) \
    init_object_dispatch_vector(InterceptId ## name, \
                                typeid(&ValidationObject::name), \
                                typeid(&StatelessValidation::name));
#endif

#if !defined(VULKANSC)
    auto init_object_dispatch_vector = [this](InterceptId id,
                                              const std::type_info& vo_typeid,
                                              const std::type_info& tt_typeid,
                                              const std::type_info& tpv_typeid,
                                              const std::type_info& tot_typeid,
                                              const std::type_info& tcv_typeid,
                                              const std::type_info& tbp_typeid,
                                              const std::type_info& tga_typeid,
                                              const std::type_info& tdp_typeid,
                                              const std::type_info& tsv_typeid) {
        for (auto item : this->object_dispatch) {
            auto intercept_vector = &this->intercept_vectors[id];
            switch (item->container_type) {
            case LayerObjectTypeThreading:
                if (tt_typeid != vo_typeid) intercept_vector->push_back(item);
                break;
            case LayerObjectTypeParameterValidation:
                if (tpv_typeid != vo_typeid) intercept_vector->push_back(item);
                break;
            case LayerObjectTypeObjectTracker:
                if (tot_typeid != vo_typeid) intercept_vector->push_back(item);
                break;
            case LayerObjectTypeCoreValidation:
                if (tcv_typeid != vo_typeid) intercept_vector->push_back(item);
                break;
            case LayerObjectTypeBestPractices:
                if (tbp_typeid != vo_typeid) intercept_vector->push_back(item);
                break;
            case LayerObjectTypeGpuAssisted:
                if (tga_typeid != vo_typeid) intercept_vector->push_back(item);
                break;
            case LayerObjectTypeDebugPrintf:
                if (tdp_typeid != vo_typeid) intercept_vector->push_back(item);
                break;
            case LayerObjectTypeSyncValidation:
                if (tsv_typeid != vo_typeid) intercept_vector->push_back(item);
                break;
            case LayerObjectTypeInstance:
            case LayerObjectTypeDevice:
                break;
            default:
                /* Chassis codegen needs to be updated for unknown validation object type */
                assert(0);
            }
        }
    };
#else
    auto init_object_dispatch_vector = [this](InterceptId id,
                                              const std::type_info& vo_typeid,
                                              const std::type_info& tpv_typeid) {
        for (auto item : this->object_dispatch) {
            auto intercept_vector = &this->intercept_vectors[id];
            switch (item->container_type) {
            case LayerObjectTypeParameterValidation:
                if (tpv_typeid != vo_typeid) intercept_vector->push_back(item);
                break;
            case LayerObjectTypeInstance:
            case LayerObjectTypeDevice:
                break;
            default:
                /* Chassis codegen needs to be updated for unknown validation object type */
                assert(0);
            }
        }
    };
#endif

    intercept_vectors.resize(InterceptIdCount);

    BUILD_DISPATCH_VECTOR(PreCallValidateGetDeviceQueue);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetDeviceQueue);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetDeviceQueue);
    BUILD_DISPATCH_VECTOR(PreCallValidateQueueSubmit);
    BUILD_DISPATCH_VECTOR(PreCallRecordQueueSubmit);
    BUILD_DISPATCH_VECTOR(PostCallRecordQueueSubmit);
    BUILD_DISPATCH_VECTOR(PreCallValidateQueueWaitIdle);
    BUILD_DISPATCH_VECTOR(PreCallRecordQueueWaitIdle);
    BUILD_DISPATCH_VECTOR(PostCallRecordQueueWaitIdle);
    BUILD_DISPATCH_VECTOR(PreCallValidateDeviceWaitIdle);
    BUILD_DISPATCH_VECTOR(PreCallRecordDeviceWaitIdle);
    BUILD_DISPATCH_VECTOR(PostCallRecordDeviceWaitIdle);
    BUILD_DISPATCH_VECTOR(PreCallValidateAllocateMemory);
    BUILD_DISPATCH_VECTOR(PreCallRecordAllocateMemory);
    BUILD_DISPATCH_VECTOR(PostCallRecordAllocateMemory);
    BUILD_DISPATCH_VECTOR(PreCallValidateMapMemory);
    BUILD_DISPATCH_VECTOR(PreCallRecordMapMemory);
    BUILD_DISPATCH_VECTOR(PostCallRecordMapMemory);
    BUILD_DISPATCH_VECTOR(PreCallValidateUnmapMemory);
    BUILD_DISPATCH_VECTOR(PreCallRecordUnmapMemory);
    BUILD_DISPATCH_VECTOR(PostCallRecordUnmapMemory);
    BUILD_DISPATCH_VECTOR(PreCallValidateFlushMappedMemoryRanges);
    BUILD_DISPATCH_VECTOR(PreCallRecordFlushMappedMemoryRanges);
    BUILD_DISPATCH_VECTOR(PostCallRecordFlushMappedMemoryRanges);
    BUILD_DISPATCH_VECTOR(PreCallValidateInvalidateMappedMemoryRanges);
    BUILD_DISPATCH_VECTOR(PreCallRecordInvalidateMappedMemoryRanges);
    BUILD_DISPATCH_VECTOR(PostCallRecordInvalidateMappedMemoryRanges);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetDeviceMemoryCommitment);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetDeviceMemoryCommitment);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetDeviceMemoryCommitment);
    BUILD_DISPATCH_VECTOR(PreCallValidateBindBufferMemory);
    BUILD_DISPATCH_VECTOR(PreCallRecordBindBufferMemory);
    BUILD_DISPATCH_VECTOR(PostCallRecordBindBufferMemory);
    BUILD_DISPATCH_VECTOR(PreCallValidateBindImageMemory);
    BUILD_DISPATCH_VECTOR(PreCallRecordBindImageMemory);
    BUILD_DISPATCH_VECTOR(PostCallRecordBindImageMemory);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetBufferMemoryRequirements);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetBufferMemoryRequirements);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetBufferMemoryRequirements);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetImageMemoryRequirements);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetImageMemoryRequirements);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetImageMemoryRequirements);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateFence);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateFence);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateFence);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyFence);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyFence);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyFence);
    BUILD_DISPATCH_VECTOR(PreCallValidateResetFences);
    BUILD_DISPATCH_VECTOR(PreCallRecordResetFences);
    BUILD_DISPATCH_VECTOR(PostCallRecordResetFences);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetFenceStatus);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetFenceStatus);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetFenceStatus);
    BUILD_DISPATCH_VECTOR(PreCallValidateWaitForFences);
    BUILD_DISPATCH_VECTOR(PreCallRecordWaitForFences);
    BUILD_DISPATCH_VECTOR(PostCallRecordWaitForFences);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateSemaphore);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateSemaphore);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateSemaphore);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroySemaphore);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroySemaphore);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroySemaphore);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateEvent);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateEvent);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateEvent);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyEvent);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyEvent);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyEvent);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetEventStatus);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetEventStatus);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetEventStatus);
    BUILD_DISPATCH_VECTOR(PreCallValidateSetEvent);
    BUILD_DISPATCH_VECTOR(PreCallRecordSetEvent);
    BUILD_DISPATCH_VECTOR(PostCallRecordSetEvent);
    BUILD_DISPATCH_VECTOR(PreCallValidateResetEvent);
    BUILD_DISPATCH_VECTOR(PreCallRecordResetEvent);
    BUILD_DISPATCH_VECTOR(PostCallRecordResetEvent);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateQueryPool);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateQueryPool);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateQueryPool);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetQueryPoolResults);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetQueryPoolResults);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetQueryPoolResults);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyBuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyBuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyBuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateBufferView);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateBufferView);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateBufferView);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyBufferView);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyBufferView);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyBufferView);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateImage);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateImage);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateImage);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyImage);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyImage);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyImage);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetImageSubresourceLayout);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetImageSubresourceLayout);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetImageSubresourceLayout);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateImageView);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateImageView);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateImageView);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyImageView);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyImageView);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyImageView);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreatePipelineCache);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreatePipelineCache);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreatePipelineCache);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyPipelineCache);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyPipelineCache);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyPipelineCache);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyPipeline);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyPipeline);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyPipeline);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyPipelineLayout);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyPipelineLayout);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyPipelineLayout);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateSampler);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateSampler);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateSampler);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroySampler);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroySampler);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroySampler);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateDescriptorSetLayout);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateDescriptorSetLayout);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateDescriptorSetLayout);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyDescriptorSetLayout);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyDescriptorSetLayout);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyDescriptorSetLayout);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateDescriptorPool);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateDescriptorPool);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateDescriptorPool);
    BUILD_DISPATCH_VECTOR(PreCallValidateResetDescriptorPool);
    BUILD_DISPATCH_VECTOR(PreCallRecordResetDescriptorPool);
    BUILD_DISPATCH_VECTOR(PostCallRecordResetDescriptorPool);
    BUILD_DISPATCH_VECTOR(PreCallValidateFreeDescriptorSets);
    BUILD_DISPATCH_VECTOR(PreCallRecordFreeDescriptorSets);
    BUILD_DISPATCH_VECTOR(PostCallRecordFreeDescriptorSets);
    BUILD_DISPATCH_VECTOR(PreCallValidateUpdateDescriptorSets);
    BUILD_DISPATCH_VECTOR(PreCallRecordUpdateDescriptorSets);
    BUILD_DISPATCH_VECTOR(PostCallRecordUpdateDescriptorSets);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateFramebuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateFramebuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateFramebuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyFramebuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyFramebuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyFramebuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateRenderPass);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateRenderPass);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateRenderPass);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroyRenderPass);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroyRenderPass);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroyRenderPass);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetRenderAreaGranularity);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetRenderAreaGranularity);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetRenderAreaGranularity);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateCommandPool);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateCommandPool);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateCommandPool);
    BUILD_DISPATCH_VECTOR(PreCallValidateResetCommandPool);
    BUILD_DISPATCH_VECTOR(PreCallRecordResetCommandPool);
    BUILD_DISPATCH_VECTOR(PostCallRecordResetCommandPool);
    BUILD_DISPATCH_VECTOR(PreCallValidateAllocateCommandBuffers);
    BUILD_DISPATCH_VECTOR(PreCallRecordAllocateCommandBuffers);
    BUILD_DISPATCH_VECTOR(PostCallRecordAllocateCommandBuffers);
    BUILD_DISPATCH_VECTOR(PreCallValidateFreeCommandBuffers);
    BUILD_DISPATCH_VECTOR(PreCallRecordFreeCommandBuffers);
    BUILD_DISPATCH_VECTOR(PostCallRecordFreeCommandBuffers);
    BUILD_DISPATCH_VECTOR(PreCallValidateBeginCommandBuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordBeginCommandBuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordBeginCommandBuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateEndCommandBuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordEndCommandBuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordEndCommandBuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateResetCommandBuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordResetCommandBuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordResetCommandBuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBindPipeline);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBindPipeline);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBindPipeline);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetViewport);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetViewport);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetViewport);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetScissor);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetScissor);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetScissor);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetLineWidth);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetLineWidth);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetLineWidth);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetDepthBias);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetDepthBias);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetDepthBias);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetBlendConstants);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetBlendConstants);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetBlendConstants);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetDepthBounds);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetDepthBounds);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetDepthBounds);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetStencilCompareMask);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetStencilCompareMask);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetStencilCompareMask);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetStencilWriteMask);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetStencilWriteMask);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetStencilWriteMask);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetStencilReference);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetStencilReference);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetStencilReference);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBindDescriptorSets);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBindDescriptorSets);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBindDescriptorSets);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBindIndexBuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBindIndexBuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBindIndexBuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBindVertexBuffers);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBindVertexBuffers);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBindVertexBuffers);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdDraw);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdDraw);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdDraw);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdDrawIndexed);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdDrawIndexed);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdDrawIndexed);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdDrawIndirect);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdDrawIndirect);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdDrawIndirect);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdDrawIndexedIndirect);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdDrawIndexedIndirect);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdDrawIndexedIndirect);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdDispatch);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdDispatch);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdDispatch);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdDispatchIndirect);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdDispatchIndirect);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdDispatchIndirect);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdCopyBuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdCopyBuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdCopyBuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdCopyImage);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdCopyImage);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdCopyImage);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBlitImage);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBlitImage);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBlitImage);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdCopyBufferToImage);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdCopyBufferToImage);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdCopyBufferToImage);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdCopyImageToBuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdCopyImageToBuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdCopyImageToBuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdUpdateBuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdUpdateBuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdUpdateBuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdFillBuffer);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdFillBuffer);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdFillBuffer);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdClearColorImage);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdClearColorImage);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdClearColorImage);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdClearDepthStencilImage);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdClearDepthStencilImage);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdClearDepthStencilImage);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdClearAttachments);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdClearAttachments);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdClearAttachments);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdResolveImage);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdResolveImage);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdResolveImage);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetEvent);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetEvent);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetEvent);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdResetEvent);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdResetEvent);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdResetEvent);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdWaitEvents);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdWaitEvents);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdWaitEvents);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdPipelineBarrier);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdPipelineBarrier);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdPipelineBarrier);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBeginQuery);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBeginQuery);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBeginQuery);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdEndQuery);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdEndQuery);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdEndQuery);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdResetQueryPool);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdResetQueryPool);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdResetQueryPool);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdWriteTimestamp);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdWriteTimestamp);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdWriteTimestamp);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdCopyQueryPoolResults);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdCopyQueryPoolResults);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdCopyQueryPoolResults);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdPushConstants);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdPushConstants);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdPushConstants);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBeginRenderPass);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBeginRenderPass);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBeginRenderPass);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdNextSubpass);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdNextSubpass);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdNextSubpass);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdEndRenderPass);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdEndRenderPass);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdEndRenderPass);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdExecuteCommands);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdExecuteCommands);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdExecuteCommands);
    BUILD_DISPATCH_VECTOR(PreCallValidateBindBufferMemory2);
    BUILD_DISPATCH_VECTOR(PreCallRecordBindBufferMemory2);
    BUILD_DISPATCH_VECTOR(PostCallRecordBindBufferMemory2);
    BUILD_DISPATCH_VECTOR(PreCallValidateBindImageMemory2);
    BUILD_DISPATCH_VECTOR(PreCallRecordBindImageMemory2);
    BUILD_DISPATCH_VECTOR(PostCallRecordBindImageMemory2);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetDeviceGroupPeerMemoryFeatures);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetDeviceGroupPeerMemoryFeatures);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetDeviceGroupPeerMemoryFeatures);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetDeviceMask);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetDeviceMask);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetDeviceMask);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdDispatchBase);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdDispatchBase);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdDispatchBase);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetImageMemoryRequirements2);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetImageMemoryRequirements2);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetImageMemoryRequirements2);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetBufferMemoryRequirements2);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetBufferMemoryRequirements2);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetBufferMemoryRequirements2);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetDeviceQueue2);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetDeviceQueue2);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetDeviceQueue2);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateSamplerYcbcrConversion);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateSamplerYcbcrConversion);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateSamplerYcbcrConversion);
    BUILD_DISPATCH_VECTOR(PreCallValidateDestroySamplerYcbcrConversion);
    BUILD_DISPATCH_VECTOR(PreCallRecordDestroySamplerYcbcrConversion);
    BUILD_DISPATCH_VECTOR(PostCallRecordDestroySamplerYcbcrConversion);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetDescriptorSetLayoutSupport);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetDescriptorSetLayoutSupport);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetDescriptorSetLayoutSupport);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdDrawIndirectCount);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdDrawIndirectCount);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdDrawIndirectCount);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdDrawIndexedIndirectCount);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdDrawIndexedIndirectCount);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdDrawIndexedIndirectCount);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateRenderPass2);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateRenderPass2);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateRenderPass2);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBeginRenderPass2);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBeginRenderPass2);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBeginRenderPass2);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdNextSubpass2);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdNextSubpass2);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdNextSubpass2);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdEndRenderPass2);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdEndRenderPass2);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdEndRenderPass2);
    BUILD_DISPATCH_VECTOR(PreCallValidateResetQueryPool);
    BUILD_DISPATCH_VECTOR(PreCallRecordResetQueryPool);
    BUILD_DISPATCH_VECTOR(PostCallRecordResetQueryPool);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetSemaphoreCounterValue);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetSemaphoreCounterValue);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetSemaphoreCounterValue);
    BUILD_DISPATCH_VECTOR(PreCallValidateWaitSemaphores);
    BUILD_DISPATCH_VECTOR(PreCallRecordWaitSemaphores);
    BUILD_DISPATCH_VECTOR(PostCallRecordWaitSemaphores);
    BUILD_DISPATCH_VECTOR(PreCallValidateSignalSemaphore);
    BUILD_DISPATCH_VECTOR(PreCallRecordSignalSemaphore);
    BUILD_DISPATCH_VECTOR(PostCallRecordSignalSemaphore);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetBufferDeviceAddress);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetBufferDeviceAddress);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetBufferDeviceAddress);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetBufferOpaqueCaptureAddress);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetBufferOpaqueCaptureAddress);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetBufferOpaqueCaptureAddress);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetDeviceMemoryOpaqueCaptureAddress);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetDeviceMemoryOpaqueCaptureAddress);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetDeviceMemoryOpaqueCaptureAddress);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetCommandPoolMemoryConsumption);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetCommandPoolMemoryConsumption);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetCommandPoolMemoryConsumption);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetFaultData);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetFaultData);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetFaultData);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateSwapchainKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateSwapchainKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateSwapchainKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetSwapchainImagesKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetSwapchainImagesKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetSwapchainImagesKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateAcquireNextImageKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordAcquireNextImageKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordAcquireNextImageKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateQueuePresentKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordQueuePresentKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordQueuePresentKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetDeviceGroupPresentCapabilitiesKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetDeviceGroupPresentCapabilitiesKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetDeviceGroupPresentCapabilitiesKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetDeviceGroupSurfacePresentModesKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetDeviceGroupSurfacePresentModesKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetDeviceGroupSurfacePresentModesKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateAcquireNextImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordAcquireNextImage2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordAcquireNextImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCreateSharedSwapchainsKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCreateSharedSwapchainsKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCreateSharedSwapchainsKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetMemoryFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetMemoryFdKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetMemoryFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetMemoryFdPropertiesKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetMemoryFdPropertiesKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetMemoryFdPropertiesKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateImportSemaphoreFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordImportSemaphoreFdKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordImportSemaphoreFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetSemaphoreFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetSemaphoreFdKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetSemaphoreFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetSwapchainStatusKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetSwapchainStatusKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetSwapchainStatusKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateImportFenceFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordImportFenceFdKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordImportFenceFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetFenceFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetFenceFdKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetFenceFdKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateAcquireProfilingLockKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordAcquireProfilingLockKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordAcquireProfilingLockKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateReleaseProfilingLockKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordReleaseProfilingLockKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordReleaseProfilingLockKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetFragmentShadingRateKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetFragmentShadingRateKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetFragmentShadingRateKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdRefreshObjectsKHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdRefreshObjectsKHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdRefreshObjectsKHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetEvent2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetEvent2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetEvent2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdResetEvent2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdResetEvent2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdResetEvent2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdWaitEvents2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdWaitEvents2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdWaitEvents2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdPipelineBarrier2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdPipelineBarrier2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdPipelineBarrier2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdWriteTimestamp2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdWriteTimestamp2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdWriteTimestamp2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateQueueSubmit2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordQueueSubmit2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordQueueSubmit2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdWriteBufferMarker2AMD);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdWriteBufferMarker2AMD);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdWriteBufferMarker2AMD);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetQueueCheckpointData2NV);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetQueueCheckpointData2NV);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetQueueCheckpointData2NV);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdCopyBuffer2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdCopyBuffer2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdCopyBuffer2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdCopyImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdCopyImage2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdCopyImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdCopyBufferToImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdCopyBufferToImage2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdCopyBufferToImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdCopyImageToBuffer2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdCopyImageToBuffer2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdCopyImageToBuffer2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBlitImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBlitImage2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBlitImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdResolveImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdResolveImage2KHR);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdResolveImage2KHR);
    BUILD_DISPATCH_VECTOR(PreCallValidateDisplayPowerControlEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordDisplayPowerControlEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordDisplayPowerControlEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateRegisterDeviceEventEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordRegisterDeviceEventEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordRegisterDeviceEventEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateRegisterDisplayEventEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordRegisterDisplayEventEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordRegisterDisplayEventEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetSwapchainCounterEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetSwapchainCounterEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetSwapchainCounterEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetDiscardRectangleEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetDiscardRectangleEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetDiscardRectangleEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateSetHdrMetadataEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordSetHdrMetadataEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordSetHdrMetadataEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateSetDebugUtilsObjectNameEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordSetDebugUtilsObjectNameEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordSetDebugUtilsObjectNameEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateSetDebugUtilsObjectTagEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordSetDebugUtilsObjectTagEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordSetDebugUtilsObjectTagEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateQueueBeginDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordQueueBeginDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordQueueBeginDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateQueueEndDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordQueueEndDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordQueueEndDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateQueueInsertDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordQueueInsertDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordQueueInsertDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBeginDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBeginDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBeginDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdEndDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdEndDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdEndDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdInsertDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdInsertDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdInsertDebugUtilsLabelEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetSampleLocationsEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetSampleLocationsEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetSampleLocationsEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetImageDrmFormatModifierPropertiesEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetImageDrmFormatModifierPropertiesEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetImageDrmFormatModifierPropertiesEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetMemoryHostPointerPropertiesEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetMemoryHostPointerPropertiesEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetMemoryHostPointerPropertiesEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateGetCalibratedTimestampsEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetCalibratedTimestampsEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetCalibratedTimestampsEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetLineStippleEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetLineStippleEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetLineStippleEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetCullModeEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetCullModeEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetCullModeEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetFrontFaceEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetFrontFaceEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetFrontFaceEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetPrimitiveTopologyEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetPrimitiveTopologyEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetPrimitiveTopologyEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetViewportWithCountEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetViewportWithCountEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetViewportWithCountEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetScissorWithCountEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetScissorWithCountEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetScissorWithCountEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdBindVertexBuffers2EXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdBindVertexBuffers2EXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdBindVertexBuffers2EXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetDepthTestEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetDepthTestEnableEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetDepthTestEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetDepthWriteEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetDepthWriteEnableEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetDepthWriteEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetDepthCompareOpEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetDepthCompareOpEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetDepthCompareOpEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetDepthBoundsTestEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetDepthBoundsTestEnableEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetDepthBoundsTestEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetStencilTestEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetStencilTestEnableEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetStencilTestEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetStencilOpEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetStencilOpEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetStencilOpEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetVertexInputEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetVertexInputEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetVertexInputEXT);
#ifdef VK_USE_PLATFORM_SCI
    BUILD_DISPATCH_VECTOR(PreCallValidateGetFenceSciSyncFenceNV);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetFenceSciSyncFenceNV);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetFenceSciSyncFenceNV);
#endif
#ifdef VK_USE_PLATFORM_SCI
    BUILD_DISPATCH_VECTOR(PreCallValidateGetFenceSciSyncObjNV);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetFenceSciSyncObjNV);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetFenceSciSyncObjNV);
#endif
#ifdef VK_USE_PLATFORM_SCI
    BUILD_DISPATCH_VECTOR(PreCallValidateImportFenceSciSyncFenceNV);
    BUILD_DISPATCH_VECTOR(PreCallRecordImportFenceSciSyncFenceNV);
    BUILD_DISPATCH_VECTOR(PostCallRecordImportFenceSciSyncFenceNV);
#endif
#ifdef VK_USE_PLATFORM_SCI
    BUILD_DISPATCH_VECTOR(PreCallValidateImportFenceSciSyncObjNV);
    BUILD_DISPATCH_VECTOR(PreCallRecordImportFenceSciSyncObjNV);
    BUILD_DISPATCH_VECTOR(PostCallRecordImportFenceSciSyncObjNV);
#endif
#ifdef VK_USE_PLATFORM_SCI
#endif
#ifdef VK_USE_PLATFORM_SCI
    BUILD_DISPATCH_VECTOR(PreCallValidateGetSemaphoreSciSyncObjNV);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetSemaphoreSciSyncObjNV);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetSemaphoreSciSyncObjNV);
#endif
#ifdef VK_USE_PLATFORM_SCI
    BUILD_DISPATCH_VECTOR(PreCallValidateImportSemaphoreSciSyncObjNV);
    BUILD_DISPATCH_VECTOR(PreCallRecordImportSemaphoreSciSyncObjNV);
    BUILD_DISPATCH_VECTOR(PostCallRecordImportSemaphoreSciSyncObjNV);
#endif
#ifdef VK_USE_PLATFORM_SCI
    BUILD_DISPATCH_VECTOR(PreCallValidateGetMemorySciBufNV);
    BUILD_DISPATCH_VECTOR(PreCallRecordGetMemorySciBufNV);
    BUILD_DISPATCH_VECTOR(PostCallRecordGetMemorySciBufNV);
#endif
#ifdef VK_USE_PLATFORM_SCI
#endif
#ifdef VK_USE_PLATFORM_SCI
#endif
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetPatchControlPointsEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetPatchControlPointsEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetPatchControlPointsEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetRasterizerDiscardEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetRasterizerDiscardEnableEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetRasterizerDiscardEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetDepthBiasEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetDepthBiasEnableEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetDepthBiasEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetLogicOpEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetLogicOpEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetLogicOpEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetPrimitiveRestartEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetPrimitiveRestartEnableEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetPrimitiveRestartEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallValidateCmdSetColorWriteEnableEXT);
    BUILD_DISPATCH_VECTOR(PreCallRecordCmdSetColorWriteEnableEXT);
    BUILD_DISPATCH_VECTOR(PostCallRecordCmdSetColorWriteEnableEXT);
};

