// *** THIS FILE IS GENERATED - DO NOT EDIT ***
// See command_validation_generator.py for modifications


/***************************************************************************
 *
 * Copyright (c) 2021 The Khronos Group Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author: Spencer Fricke <s.fricke@samsung.com>
 *
 ****************************************************************************/

#pragma once
#include <array>

// Used as key for maps of all vkCmd* calls
// Does not include vkBeginCommandBuffer/vkEndCommandBuffer
typedef enum CMD_TYPE {
    CMD_NONE = 0,
    CMD_BEGINDEBUGUTILSLABELEXT = 1,
    CMD_BEGINQUERY = 2,
    CMD_BEGINRENDERPASS = 3,
    CMD_BEGINRENDERPASS2 = 4,
    CMD_BINDDESCRIPTORSETS = 5,
    CMD_BINDINDEXBUFFER = 6,
    CMD_BINDPIPELINE = 7,
    CMD_BINDVERTEXBUFFERS = 8,
    CMD_BINDVERTEXBUFFERS2EXT = 9,
    CMD_BLITIMAGE = 10,
    CMD_BLITIMAGE2KHR = 11,
    CMD_CLEARATTACHMENTS = 12,
    CMD_CLEARCOLORIMAGE = 13,
    CMD_CLEARDEPTHSTENCILIMAGE = 14,
    CMD_COPYBUFFER = 15,
    CMD_COPYBUFFER2KHR = 16,
    CMD_COPYBUFFERTOIMAGE = 17,
    CMD_COPYBUFFERTOIMAGE2KHR = 18,
    CMD_COPYIMAGE = 19,
    CMD_COPYIMAGE2KHR = 20,
    CMD_COPYIMAGETOBUFFER = 21,
    CMD_COPYIMAGETOBUFFER2KHR = 22,
    CMD_COPYQUERYPOOLRESULTS = 23,
    CMD_DISPATCH = 24,
    CMD_DISPATCHBASE = 25,
    CMD_DISPATCHINDIRECT = 26,
    CMD_DRAW = 27,
    CMD_DRAWINDEXED = 28,
    CMD_DRAWINDEXEDINDIRECT = 29,
    CMD_DRAWINDEXEDINDIRECTCOUNT = 30,
    CMD_DRAWINDIRECT = 31,
    CMD_DRAWINDIRECTCOUNT = 32,
    CMD_ENDDEBUGUTILSLABELEXT = 33,
    CMD_ENDQUERY = 34,
    CMD_ENDRENDERPASS = 35,
    CMD_ENDRENDERPASS2 = 36,
    CMD_EXECUTECOMMANDS = 37,
    CMD_FILLBUFFER = 38,
    CMD_INSERTDEBUGUTILSLABELEXT = 39,
    CMD_NEXTSUBPASS = 40,
    CMD_NEXTSUBPASS2 = 41,
    CMD_PIPELINEBARRIER = 42,
    CMD_PIPELINEBARRIER2KHR = 43,
    CMD_PUSHCONSTANTS = 44,
    CMD_REFRESHOBJECTSKHR = 45,
    CMD_RESETEVENT = 46,
    CMD_RESETEVENT2KHR = 47,
    CMD_RESETQUERYPOOL = 48,
    CMD_RESOLVEIMAGE = 49,
    CMD_RESOLVEIMAGE2KHR = 50,
    CMD_SETBLENDCONSTANTS = 51,
    CMD_SETCOLORWRITEENABLEEXT = 52,
    CMD_SETCULLMODEEXT = 53,
    CMD_SETDEPTHBIAS = 54,
    CMD_SETDEPTHBIASENABLEEXT = 55,
    CMD_SETDEPTHBOUNDS = 56,
    CMD_SETDEPTHBOUNDSTESTENABLEEXT = 57,
    CMD_SETDEPTHCOMPAREOPEXT = 58,
    CMD_SETDEPTHTESTENABLEEXT = 59,
    CMD_SETDEPTHWRITEENABLEEXT = 60,
    CMD_SETDEVICEMASK = 61,
    CMD_SETDISCARDRECTANGLEEXT = 62,
    CMD_SETEVENT = 63,
    CMD_SETEVENT2KHR = 64,
    CMD_SETFRAGMENTSHADINGRATEKHR = 65,
    CMD_SETFRONTFACEEXT = 66,
    CMD_SETLINESTIPPLEEXT = 67,
    CMD_SETLINEWIDTH = 68,
    CMD_SETLOGICOPEXT = 69,
    CMD_SETPATCHCONTROLPOINTSEXT = 70,
    CMD_SETPRIMITIVERESTARTENABLEEXT = 71,
    CMD_SETPRIMITIVETOPOLOGYEXT = 72,
    CMD_SETRASTERIZERDISCARDENABLEEXT = 73,
    CMD_SETSAMPLELOCATIONSEXT = 74,
    CMD_SETSCISSOR = 75,
    CMD_SETSCISSORWITHCOUNTEXT = 76,
    CMD_SETSTENCILCOMPAREMASK = 77,
    CMD_SETSTENCILOPEXT = 78,
    CMD_SETSTENCILREFERENCE = 79,
    CMD_SETSTENCILTESTENABLEEXT = 80,
    CMD_SETSTENCILWRITEMASK = 81,
    CMD_SETVERTEXINPUTEXT = 82,
    CMD_SETVIEWPORT = 83,
    CMD_SETVIEWPORTWITHCOUNTEXT = 84,
    CMD_UPDATEBUFFER = 85,
    CMD_WAITEVENTS = 86,
    CMD_WAITEVENTS2KHR = 87,
    CMD_WRITEBUFFERMARKER2AMD = 88,
    CMD_WRITETIMESTAMP = 89,
    CMD_WRITETIMESTAMP2KHR = 90,
    CMD_RANGE_SIZE = 91
} CMD_TYPE;

static const std::array<const char *, CMD_RANGE_SIZE> kGeneratedCommandNameList = {{
    "Command_Undefined",
    "vkCmdBeginDebugUtilsLabelEXT",
    "vkCmdBeginQuery",
    "vkCmdBeginRenderPass",
    "vkCmdBeginRenderPass2",
    "vkCmdBindDescriptorSets",
    "vkCmdBindIndexBuffer",
    "vkCmdBindPipeline",
    "vkCmdBindVertexBuffers",
    "vkCmdBindVertexBuffers2EXT",
    "vkCmdBlitImage",
    "vkCmdBlitImage2KHR",
    "vkCmdClearAttachments",
    "vkCmdClearColorImage",
    "vkCmdClearDepthStencilImage",
    "vkCmdCopyBuffer",
    "vkCmdCopyBuffer2KHR",
    "vkCmdCopyBufferToImage",
    "vkCmdCopyBufferToImage2KHR",
    "vkCmdCopyImage",
    "vkCmdCopyImage2KHR",
    "vkCmdCopyImageToBuffer",
    "vkCmdCopyImageToBuffer2KHR",
    "vkCmdCopyQueryPoolResults",
    "vkCmdDispatch",
    "vkCmdDispatchBase",
    "vkCmdDispatchIndirect",
    "vkCmdDraw",
    "vkCmdDrawIndexed",
    "vkCmdDrawIndexedIndirect",
    "vkCmdDrawIndexedIndirectCount",
    "vkCmdDrawIndirect",
    "vkCmdDrawIndirectCount",
    "vkCmdEndDebugUtilsLabelEXT",
    "vkCmdEndQuery",
    "vkCmdEndRenderPass",
    "vkCmdEndRenderPass2",
    "vkCmdExecuteCommands",
    "vkCmdFillBuffer",
    "vkCmdInsertDebugUtilsLabelEXT",
    "vkCmdNextSubpass",
    "vkCmdNextSubpass2",
    "vkCmdPipelineBarrier",
    "vkCmdPipelineBarrier2KHR",
    "vkCmdPushConstants",
    "vkCmdRefreshObjectsKHR",
    "vkCmdResetEvent",
    "vkCmdResetEvent2KHR",
    "vkCmdResetQueryPool",
    "vkCmdResolveImage",
    "vkCmdResolveImage2KHR",
    "vkCmdSetBlendConstants",
    "vkCmdSetColorWriteEnableEXT",
    "vkCmdSetCullModeEXT",
    "vkCmdSetDepthBias",
    "vkCmdSetDepthBiasEnableEXT",
    "vkCmdSetDepthBounds",
    "vkCmdSetDepthBoundsTestEnableEXT",
    "vkCmdSetDepthCompareOpEXT",
    "vkCmdSetDepthTestEnableEXT",
    "vkCmdSetDepthWriteEnableEXT",
    "vkCmdSetDeviceMask",
    "vkCmdSetDiscardRectangleEXT",
    "vkCmdSetEvent",
    "vkCmdSetEvent2KHR",
    "vkCmdSetFragmentShadingRateKHR",
    "vkCmdSetFrontFaceEXT",
    "vkCmdSetLineStippleEXT",
    "vkCmdSetLineWidth",
    "vkCmdSetLogicOpEXT",
    "vkCmdSetPatchControlPointsEXT",
    "vkCmdSetPrimitiveRestartEnableEXT",
    "vkCmdSetPrimitiveTopologyEXT",
    "vkCmdSetRasterizerDiscardEnableEXT",
    "vkCmdSetSampleLocationsEXT",
    "vkCmdSetScissor",
    "vkCmdSetScissorWithCountEXT",
    "vkCmdSetStencilCompareMask",
    "vkCmdSetStencilOpEXT",
    "vkCmdSetStencilReference",
    "vkCmdSetStencilTestEnableEXT",
    "vkCmdSetStencilWriteMask",
    "vkCmdSetVertexInputEXT",
    "vkCmdSetViewport",
    "vkCmdSetViewportWithCountEXT",
    "vkCmdUpdateBuffer",
    "vkCmdWaitEvents",
    "vkCmdWaitEvents2KHR",
    "vkCmdWriteBufferMarker2AMD",
    "vkCmdWriteTimestamp",
    "vkCmdWriteTimestamp2KHR",
}};
