name: Fork CI (push)

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

concurrency:
  group: fork-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vvl:
    # never run if this file ever ends up upstream
    if: github.repository != 'KhronosGroup/Vulkan-ValidationLayers'
    uses: ./.github/workflows/vvl.yml
    secrets: inherit
